# ABOUT: How to compile manually

# The syntax is:
# c-compiler file_name.c -o binary_name

# Here's how to compile the `main.c` file in this project into 
# a binary executable called `main`

# mkdir -p build
# clang -std=c23 src/main.c -o build/main

# To run the binary executable, run this command:
# ./build/main

# _____________________________________________________________________________
