[tools]
clang = "latest"
clang-format = "latest"
ninja = "latest"

[settings]
task.timings = false

[tasks.build]
description = "🔨 Build the project with ninja" 
quiet = true
run = """
ninja --quiet
ninja -t compdb > compile_commands.json
"""

[tasks.dev]
description = "🇨 Run the project" 
quiet = true
run = """
mise build
./build/bin/main
"""

[tasks.clean]
description = "🧼 Clean the project directory" 
quiet = true
run = """
rm -rf .cache/ build/ .ninja_log compile_commands.json
"""
